# Generated by Django 4.2.28 on 2026-02-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentexam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='LegacyQuestion',
        ),
    ]
